### ISSUE TITLE
Cannot find and download engine build

### ISSUE THREAD

**Issue by katyo** [flutter-rs/cargo-flutter#7]
```
$ cargo flutter --format appimage build --release
Downloading flutter engine 0 of 0
Starting download from https://github.com/flutter-rs/engine-builds/releases/download/f-09d892b3bf5d24a6d7b942586203cc57d226dbf1/linux_x64-host_release.zip
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Error { description: "HTTP response code said error", code: 22, extra: None }', src/libcore/result.rs:1165:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
Error: Os { code: 2, kind: NotFound, message: "No such file or directory" }
```

**Comment by dvc94ch** [comment]
What flutter version are you using? We build the engine for stable, beta and dev, so that error means we don't have the build or the build is not complete yet. If you are on master you need to run `flutter channel dev` and in any case run `flutter upgrade`.

**Comment by katyo** [comment]
Oh, it seems I have tried to compile [flutter-app-demo](https://github.com/flutter-rs/flutter-app-demo) whithout any changes.

**Comment by dvc94ch** [comment]
Fixed in https://github.com/flutter-rs/cargo-flutter/commit/d441700802ac91b1dcb469ddbd251f8d80d738d1
