### ISSUE TITLE
Feature request: benchmarking

### ISSUE THREAD

**Issue by j4qfrost** [flutter-rs/cargo-flutter#8]
It would be really nice to have this for locating bottlenecks. Not sure how this would be integrated yet. All the threads I've read say criterion is really good. I imagine being able to call benchmarks with ```cargo flutter bench```. Thoughts?

**Comment by dvc94ch** [comment]
You should already be able to do that. Does it not work?

**Comment by j4qfrost** [comment]
Looks like this is just my lack of experience with rust. I thought the subcommand had to be explicitly added.
